/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package antlr4.example;

import antlr4.sql.base.PlSqlParser;
import antlr4.sql.base.PlSqlParserBaseVisitor;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}

