/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    antlr
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDir("${buildDir}/generated-src/antlr/main")
        }
    }
}

dependencies {
    antlr("org.antlr:antlr4:4.5")
    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:29.0-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("antlr4.example.App")
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}

tasks.generateGrammarSource {
    maxHeapSize = "64m"
    arguments = arguments + listOf("-package", "antlr4.sql.base","-visitor", "-long-messages")
    outputDirectory = File("${buildDir}/generated-src/antlr/main/antlr4/sql/base");
}
